# ------------------------------------------------------------------------------
# Build config
# ------------------------------------------------------------------------------

# Templates
templates:        templates
partials:         <%= site.templates %>/partials/**/*.swig
helpers:          <%= site.templates %>/helpers
layouts:          <%= site.templates %>/layouts
pages:            <%= site.templates %>/pages
layout:           default.swig

# Data
data:             data

# Destination
dest:             _gh_pages
assets:           /assets
css:              <%= site.assets %>/css
img:              <%= site.assets %>/img
js:               <%= site.assets %>/js

# Theme
theme:            theme
sass:             <%= site.theme %>/scss
theme_img:        <%= site.theme %>/img
theme_js:         <%= site.theme %>/js

# Dist
dist_css:        <%= site.dest %>/<%= site.css %>
dist_img:        <%= site.dest %>/<%= site.img %>
dist_js:         <%= site.dest %>/<%= site.js %>

# Extensions
plugins:
  - assemble-contrib-anchors
  - assemble-contrib-wordcount
  - assemble-contrib-toc

# ------------------------------------------------------------------------------
# Project metadata
# ------------------------------------------------------------------------------

author:
  name:           Kenneth Auchenberg
  twitter:        auchenberg
  url:            https://kenneth.io
ga:               

title:            'DevTools Rocks'
description:      'Find resources that help you build lightning fast websites'
keywords:         'devtools, developer tooling, browser devtools'

url:              https://devtools.rocks
github:
    repo:         https://github.com/auchenberg/devtools.rocks
    issues:       https://github.com/auchenberg/devtools.rocks/issues


tool_types:
  - node
  - grunt
  - gulp
  - broccoli
